FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

WORKDIR /app

COPY pyproject.toml pyproject.toml
COPY uv.lock uv.lock
COPY README.md README.md
COPY src/ src/

RUN uv sync --locked 

COPY . .

# This Dockerfile is intended to be used as a base for other services,
# so no CMD or ENTRYPOINT is specified here. 