name: "bedroom"

camera:
  uri: "1"

instructions:
  - "The baby shouldn't do anything dangerous."
  - "An adult should be in the room with the baby if the baby is awake."
  - "The baby shouldn't try to climb out of the crib."